os: linux
dist: bionic
language: java
before_install:
  # default pandoc is too old -> install a newer version manually
  - PANDOC_VERSION="2.9.2"
  - pandoc_deb="pandoc-${PANDOC_VERSION}-1-amd64.deb"
  - wget "https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/${pandoc_deb}"
  - sudo dpkg -i ${pandoc_deb}
  - rm ${pandoc_deb}

  # default textlife from apt-get is too old
  # install the latest texlife version manually
  - REMOTE="http://mirror.ctan.org/systems/texlive/tlnet"
  - INSTALL="/tmp/install-texlive"
  - mkdir -p $INSTALL
  - curl -sSL $REMOTE/install-tl-unx.tar.gz | tar -xzv -C $INSTALL --strip-components=1
  - sudo $INSTALL/install-tl -no-gui -profile .texlife.profile
  - VERSION=$($INSTALL/install-tl --version | grep 'version' | grep -o '[0-9]\{4\}')
  - PLATFORM=$($INSTALL/install-tl --print-platform)
  - TEXLIVE_DIR="/usr/local/texlive/${VERSION}"
  - TEXBIN="/usr/local/texlive/${VERSION}/bin/${PLATFORM}"
  - export "PATH=$TEXBIN:$PATH"

  # initialization for tlmgr
  - sudo apt-get install xzdec
  - tlmgr init-usertree

  # install pdftoppm for rendering the PDFs
  - sudo apt-get install poppler-utils

  # for executing python based pandoc filters install python and pip
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade setuptools
  - sudo pip3 install wheel

  # for converting to mobi
  - sudo apt-get install calibre

  # install python filters
  - pip3 install pandoc-latex-environment


  - sudo chown -hR $(whoami) "$TEXLIVE_DIR"
  # packages specified in the template
  - tlmgr install adjustbox background bidi csquotes footmisc footnotebackref fvextra mdframed pagecolor sourcecodepro sourcesanspro titling ulem upquote xurl

  # trial and error
  - tlmgr install letltxmacro zref everypage framed collectbox

  # packages needed for the template
  - tlmgr install xecjk filehook unicode-math ucharcat ly1 mweights mdframed needspace

  # packages needed for the books
  - tlmgr install awesomebox fontawesome5 newunicodechar
script:
  - make -C volume1 all
  - make -C volume1 png
